warmup_workout_data = [
    {"exercise": "EMOM 10\nOdd: Thrusters increase weight\nEven: 15 cal Row\n15 Knee Tucks Every Other Round"},
    {"exercise": "EMOM 10\nOdd: Back Squat increase weight\nEven: 15 cal row\n15 Knee Tucks Every Other Round"},
    {"exercise": "EMOM 6\n5 x Back Squat\nFor Time: 10 - 1\n10 DB Snatch Right\n10 DB Snatch Left\n10 DG Goblet Squat"},
    {"exercise": "EMOM 6\n3 Hang Squat Cleans\n8 Minute Ladder(add 2 reps per round):\n6 Cal Row\n6 Wall Balls\n"},
    {"exercise": "EMOM 10\n1. Bench Press 8, 8, 6, 6, 4\n2. Bent Over Row 8"},
    {"exercise": "EMOM 10\nBack Squat 5, 5, 4, 4, 3, 3, 2, 2, 1, 1"},
    {"exercise": "EMOM 10\nBB Bench Press 12, 10, 8, 8, 6\nBent Over Reverse Flys 12"},
    {"exercise": "EMOM 10\nDB Bench Press\n1 Hanging poer clean"},
    {"exercise": "EMOM 8\nFront Squat 4, 3, 2, 1\n3 x Box Jump\nThen:\n20 x KB Jump goblet squat"},
    {"exercise": "EMOM 12\n12 x Kneeling Shoulder Press\n8 x Heaves\n20 Sec Suitcase carry ES"},
    {"exercise": "EMOM 8\n5 x DB Bench Complex(Single, Single, Double)\n2 x Hang power clean\nThen:\nMax Press ups and Pullups"},
    {"exercise": "EMOM 10\n8 x DB Bench press\n1 x Hang power clean"},
    {"exercise": "EMOM 8\nFront squat 4, 4, 2, 2\nAt 8 mins\n3 x Box jump\n25 x Back Squat with last front squat weight"},
    {"exercise": "EMOM 8\nBB Bench press 12, 10, 8, 12\n12 x Bent Over reverse flys"},
    {"exercise": "EMOM 8\nFront Squats 5, 3, 2, 1\nBox JUmps x 3\nAt 8 min. 32 Alt Reverse Lunges"},
    {"exercise": "EMOM 10\n5 x Back Squats\nBox JUmps x 3"},
    {"exercise": "EMOM 12\n12 x Barbell Shoulder press\n12 x SA Row\n15 x Ab matt situps + 20 Toe Touch"},
    {"exercise": "EMOM 8\nFront Squats 4, 4, 2, 2\n3 x Box Jumps\n@ 8 mins:\n25 x Back Squats"},
    {"exercise": "EMOM 12\n10 x BD Push Press + 10 DB Bent Over Row\n8 x T2B or Knees to Chest\n20 Sec side Plank hip drops each side"},
    {"exercise": "EMOM 8\nBB Bench Press 12, 10, 8, 12\n12 x B/O Rev Flies"},
    {"exercise": "EMOM 8\nFront Squat 5, 3, 2, 1\n3 x Box Jumps\n@ 8 min:\n32 x Alternating reverse lunges"},
    {"exercise": "EMOM 12\n16 x DB Shoulder press\n10 x Barbel Heaves\n15 x Reverse crunches + 20 x Toe Touch"},
    {"exercise": "EMOM 10\nBarbell Bench Press 10, 8, 6, 4, 10\n10 x SA Row"},
    {"exercise": "12 Min Time:\n25 Cal C2 Bike\n25 x Hang Clean and Jerk\n25 x Burpee Pull ups\nMax Cals Ski"},
    {"exercise": "EMOM 10\nDeadlift:\n4, 4, 3, 3, 3, 2, 2, 2, 1, 1\nIncrease weight with each set"},
]